### ISSUE TITLE
ModelMapper 관련

### ISSUE THREAD

**Issue by endb1228** [bit-o-gi/project#23]
봉규님 코드를 보면 ModelMapper를 클래스마다 static하게, 혹은 api가 호출될 때마다 생성하고 계십니다.
ModelMapper는 생성할 때 리소스를 많이 잡아먹기 때문에 싱글톤 형태로 하나만 만들어놓고 사용하는 것이 일반적인 것으로 알고 있어요.

**Comment by bong94688** [comment]
Configation에 설정하여 사용하는 방식을 사용하지만 제가알기로는 Api 호출할때마다 static 하게 올라간다하더라도 .  필요 없는 인스턴스는 가비지 컬렉터에 의해 적절히 정리된다 생각해서 사용하였고 , 그리고 추후 멀티스레드 구성에 각 스레드의 안정성을 증대 시킬수있습니다.
그렇지만 메모리 부족 현상 , **적절한 합의** 가 있다면 독립성이 있는 Dto 클래스외에는 Configation에 선언하고 사용할수는 있을것같습니다.

**Comment by bong94688** [comment]
https://velog.io/@bong9468/ModelMapper-%EC%9D%98-Dto-%ED%99%9C%EC%9A%A9
